# Generated by Django 3.2.9 on 2021-11-29 21:41

from django.db import migrations, models
import minecraftpaintings.models


class Migration(migrations.Migration):

    dependencies = [
        ('minecraftpaintings', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paintings',
            name='painting_Img',
            field=models.ImageField(storage=minecraftpaintings.models.OverwriteStorage(), upload_to=minecraftpaintings.models.new_file_name),
        ),
    ]
